### PR TITLE
rework CMK Helm chart to allow scaling up and down

### PR DESCRIPTION
**Pull request by przemeklal**
This patch replaces `cmk cluster-init` deployment with Helm templates.
Single Daemonset is created to run init, discover and install commands
in the initContainers, then reconcile and nodereport are started as
regular running containers in the Pod. Using nodeAffinity allows for
scaling and provides idempotency between subsequent deployments.

It also fixes issue where `helm delete --purge` command would remove
cluster-init pod and RBAC/serviceaccount only, leaving any other resources
in not fully functional state.

### CODE REVIEW

**Comment by przemeklal** [comment]
@lmdaly @michaelspedersen could you please take a look?

**Comment by michaelspedersen** [comment]
While I don't know the exact details on how CMK deploys through cluster-init, I like the idea of running it as a daemonset. I also haven't tested out the update, but if it deploys as expected for you then I think it is good

**Comment by przemeklal** [comment]
CMK cluster-init creates pretty much similar set of K8s resources, but does it from the Python code, also for some reason creates separate daemonsets for each of the nodes and some installation steps are performed using job-like pods, which isn't the most elegant solution. But the biggest motivation was to be able to uninstall/reinstall/scale up CMK using Helm only - in the first version of the Helm chart only cluster-init was deployed with helm, so deleting Helm chart was deleting only the cluster-init pod, leaving everything up and running else like nothing happened.

hey @lmdaly, do you think could we go ahead and merge this PR?

**Comment by lmdaly** [comment]
@przemeklal would it be possible to remove CMK using the CMK uninstall in a Helm chart? How this way allow for scale up, when a new node is added the helm chart is just deployed there?

**Comment by przemeklal** [comment]
> would it be possible to remove CMK using the CMK uninstall in a Helm chart?

Unfortunately no. `helm delete` can only remove resources that it created itself during `helm install` - if anything else is created (by cluster-init for example), Helm isn't aware of them and has no idea that something extra should be removed. cluster-init and uninstall commands in the CMK basically overlap with the Helm functionality.

> How this way allow for scale up, when a new node is added the helm chart is just deployed there?

Helm chart is deployed cluster-wide only once. But it creates a single DaemonSet for CMK to run on all nodes automatically - when the new Kubernetes node is added, CMK pod is created automatically on this new node with init, install, discover executed first as the initContainers and then reconcile and nodereport running as usually - but everything is part of a single DaemonSet. This was also impossible with the cluster-init.

There's also an option to set nodeAffinity (cmk_hosts_list value in the Helm values) - in that case all nodes are added to the nodeAffinity in the DaemonSet spec and pods are scheduled only on the matching nodes. This is also mutable - `helm upgrade` will update the DaemonSet spec with new values.

Also - there's nothing really new that isn't in the CMK repo already - we already had separate example pod specs for all commands there.

**Comment by lmdaly** [comment]
@przemeklal okay thanks for the explanations, LGTM to me then

**Pull request merged**
